{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ (index .Values.ingress.hosts 0).host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "fullname" . }}-api
            port:
              number: {{ .Values.service.apiPort }}
  - host: {{ .Values.ingress.rabbitmqHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "fullname" . }}-rabbitmq
            port:
              number: {{ .Values.rabbitmq.managementPort }}
{{- end }}
