apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-postgres
spec:
  selector:
    matchLabels:
      app: {{ include "fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "fullname" . }}-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "fullname" . }}-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.database }}"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: {{ include "fullname" . }}-pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-postgres
spec:
  type: ClusterIP
  selector:
    app: {{ include "fullname" . }}-postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      name: postgres
