apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fullname" . }}-rabbitdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rabbitmq.persistentVolume.size }}
